#文件传输限制
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  data:
    solr:


#配置数据源
  datasource:
    url: jdbc:mysql://localhost/learning_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#jdbc配置
  jdbc:
    template:
      query-timeout: 5
#redis配置
#  redis:
#    host:
#    port:
#    password:
#    client-name:
#    lettuce:
#      pool:
#        max-active:
#        min-idle:

mybatis:
#指定全局配置文件
#  config-location: classpath:mybatis/mybatis-config.xml
#指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
#  注解模式：指定全局配置文件的指定项
  configuration:
    map-underscore-to-camel-case: true