# 服务器配置
server:
  port: 8090
  servlet:
    context-path: /
# Spring配置
spring:
  # FreeMarker配置
  # 模版资源加载路径(默认就是classpath:/templates/，所以不配置也一样)
  freemarker:
    template-loader-path: classpath:/templates/
    # 后缀名配置
    suffix: .ftl
    # 缓存
    cache: false
  # multipart配置
  servlet:
    multipart:
      # 支持最大文件大小
      max-file-size: 200MB
      # 支持最大请求大小
      max-request-size: 200MB
# 自定义配置
jar:
  # 上传文件服务器存储绝对路径（注意：路径一定要以/结尾，否则获取上传文件时会报404）
  # window server：F://app/object/upload/
  # linux server：/app/object/upload/
  upload-path: E://chrome
  # 上传文件网络请求相对路径
  server-file-path: /upload
  # 上传图片大小（单位：MB）
  upload-image-size: 1.0
  # 上传视频大小（单位：MB）
  upload-video-size: 200.0
  # 上传文件大小（单位：MB）
  upload-file-size: 10.0